name: 💡 Feature Request
description: Suggest an idea to improve the platform
title: "[Feature] "
labels: ["🧠 idea"]
body:
  - type: markdown
    attributes:
      value: "## 🧠 What's your idea?"
  - type: textarea
    id: idea
    attributes:
      label: Describe the feature
      placeholder: What problem does this solve?
    validations:
      required: true
